sites:
  - name: Buyer Opinin
    follow_desc: 
    url: "https://www.the-buyer.net/opinion"
    block_css: " main  div  a"  # 父元素的 CSS 选择器
    title_css: "h3"  # 在父元素内部的标题选择器
    description_css: "h3"
    link_css: 
    use_headless_browser: true
